"use client";

import { Sparkles } from "lucide-react";

export default function AIInsightCard({ insight, loading = false }) {
  if (loading) {
    return (
      <div className="rounded-2xl border border-indigo-500/20 bg-gradient-to-br from-indigo-900/20 to-slate-800/40 p-5">
        <div className="flex items-center gap-2 mb-4">
          <div className="w-6 h-6 rounded-lg skeleton" />
          <div className="w-32 h-4 rounded skeleton" />
        </div>
        <div className="space-y-2">
          <div className="w-full h-3 rounded skeleton" />
          <div className="w-5/6 h-3 rounded skeleton" />
          <div className="w-4/6 h-3 rounded skeleton" />
        </div>
      </div>
    );
  }

  if (!insight) return null;

  return (
    <div className="relative overflow-hidden rounded-2xl border border-indigo-500/25 bg-gradient-to-br from-indigo-900/25 via-slate-800/40 to-purple-900/10 p-5 animate-fade-in">
      {/* Glow top-right */}
      <div className="absolute -top-8 -right-8 w-32 h-32 rounded-full bg-indigo-600/10 blur-2xl pointer-events-none" />

      {/* Header */}
      <div className="flex items-center gap-2 mb-3">
        <div className="p-1.5 rounded-lg bg-indigo-500/20">
          <Sparkles size={14} className="text-indigo-300" />
        </div>
        <span className="text-sm font-semibold text-indigo-300">Ringkasan AI</span>
        <span className="ml-auto text-[10px] text-slate-500 bg-slate-800/60 px-2 py-0.5 rounded-full border border-slate-700">
          Generated by n8n + LLM
        </span>
      </div>

      {/* Summary text */}
      <p className="text-sm text-slate-300 leading-relaxed">{insight.summary}</p>

      {/* Anomaly indicator */}
      {insight.anomaly && (
        <div className="mt-3 flex items-center gap-2 text-amber-400 bg-amber-500/10 border border-amber-500/20 rounded-lg px-3 py-2">
          <span className="text-base">⚠️</span>
          <span className="text-xs font-medium">Anomali terdeteksi dalam data ini — lihat detail di bawah.</span>
        </div>
      )}

      {/* Chart type badge */}
      <div className="mt-3 flex items-center gap-2">
        <span className="text-[10px] text-slate-500">Tipe visualisasi rekomendasi AI:</span>
        <span className="text-[10px] font-semibold text-indigo-300 bg-indigo-500/15 px-2 py-0.5 rounded-full capitalize border border-indigo-500/20">
          {insight.chart_type} chart
        </span>
      </div>
    </div>
  );
}
